#!/usr/bin/env python3
"""Deploy the Fabric IQ Ontology definition generated by
generate_fabric_iq_definition.py, via direct Fabric REST API calls.

Not done through the `fabric_ontology` Terraform resource: verified live
that Terraform-issued create/update calls for this resource reliably
fail with an opaque `ALMOperationImportFailed` error against this
tenant, while byte-identical requests issued directly against the
Fabric REST API (same auth, same rendered payload) succeed every time --
both create (202 + polled LRO -> Succeeded) and update (200 sync). The
difference is in the provider's request handling, not the payload, so
this script -- same shape as run_kql.py -- sidesteps it rather than
fighting an unreliable path.

Auth: `az login` (AzureCliCredential), same pattern as the rest of
infra.

Usage:
    FABRIC_WORKSPACE_ID=... FABRIC_KQL_DATABASE_ITEM_ID=... \\
    FABRIC_CLUSTER_URI=... FABRIC_KQL_DATABASE_NAME=... \\
        uv run --with azure-identity --with requests \\
        deploy_fabric_iq_ontology.py
"""

import base64
import json
import os
import time
from pathlib import Path

import requests
from azure.identity import AzureCliCredential

HERE = Path(__file__).parent
DEFINITION_DIR = HERE / "fabric_iq"
DISPLAY_NAME = "ChocolateFactory"
API_BASE = "https://api.fabric.microsoft.com/v1"


def get_token() -> str:
    credential = AzureCliCredential()
    return credential.get_token("https://api.fabric.microsoft.com/.default").token


def render_tokens(text: str, tokens: dict[str, str]) -> str:
    for key, value in tokens.items():
        text = text.replace("{{ ." + key + " }}", value)
    return text


def build_definition_parts(tokens: dict[str, str]) -> list[dict]:
    parts = []
    for path in sorted(DEFINITION_DIR.rglob("*")):
        if not path.is_file():
            continue
        rel_path = str(path.relative_to(DEFINITION_DIR))
        target_path = rel_path.removesuffix(".tmpl")
        content = render_tokens(path.read_text(), tokens)
        payload = base64.b64encode(content.encode()).decode()
        parts.append({"path": target_path, "payload": payload, "payloadType": "InlineBase64"})
    return parts


def find_existing_item(session: requests.Session, workspace_id: str) -> str | None:
    resp = session.get(f"{API_BASE}/workspaces/{workspace_id}/items", params={"type": "Ontology"})
    resp.raise_for_status()
    for item in resp.json().get("value", []):
        if item["displayName"] == DISPLAY_NAME:
            return item["id"]
    return None


def wait_for_operation(session: requests.Session, operation_url: str) -> None:
    while True:
        resp = session.get(operation_url)
        resp.raise_for_status()
        status = resp.json()
        if status["status"] == "Succeeded":
            return
        if status["status"] == "Failed":
            raise RuntimeError(f"Operation failed: {status.get('error')}")
        time.sleep(int(resp.headers.get("Retry-After", 5)))


def main() -> None:
    workspace_id = os.environ["FABRIC_WORKSPACE_ID"]
    tokens = {
        "WorkspaceId": workspace_id,
        "EventhouseId": os.environ["FABRIC_KQL_DATABASE_ITEM_ID"],
        "ClusterUri": os.environ["FABRIC_CLUSTER_URI"],
        "DatabaseName": os.environ["FABRIC_KQL_DATABASE_NAME"],
        "LakehouseId": os.environ["FABRIC_LAKEHOUSE_ID"],
    }

    session = requests.Session()
    session.headers["Authorization"] = f"Bearer {get_token()}"

    parts = build_definition_parts(tokens)
    print(f"rendered {len(parts)} definition part(s) from {DEFINITION_DIR}")

    existing_id = find_existing_item(session, workspace_id)
    if existing_id:
        print(f"updating existing ontology item {existing_id}")
        resp = session.post(
            f"{API_BASE}/workspaces/{workspace_id}/items/{existing_id}/updateDefinition",
            params={"updateMetadata": "false"},
            json={"definition": {"parts": parts}},
        )
        resp.raise_for_status()
        if resp.status_code == 202:
            wait_for_operation(session, resp.headers["Location"])
        print(f"updated ontology item {existing_id}")
    else:
        print("creating new ontology item")
        resp = session.post(
            f"{API_BASE}/workspaces/{workspace_id}/items",
            json={
                "type": "Ontology",
                "displayName": DISPLAY_NAME,
                "definition": {"parts": parts},
            },
        )
        resp.raise_for_status()
        if resp.status_code == 202:
            wait_for_operation(session, resp.headers["Location"])
            item_id = find_existing_item(session, workspace_id)
        else:
            item_id = resp.json()["id"]
        print(f"created ontology item {item_id}")


if __name__ == "__main__":
    main()
